### ISSUE TITLE
omero web nginx config is ignored

### ISSUE THREAD

**Issue by manics** [ome/ansible-role-omero-web#17]
Nginx is configured before the systemd setup. This means omero-web configuration properties that affect the generated nginx config file (e.g. `omero.web.prefix`) are ignored.

**Comment by joshmoore** [comment]
How critical is this, @manics ?

**Comment by manics** [comment]
If anyone sets `omero.web.prefix` their OMERO.web won't work. I suspect this has always been the case, and no-ones reported it until I discovered it the other day.

**Comment by manics** [comment]
Turns out I fixed it and forgot to open the PR: https://github.com/openmicroscopy/ansible-role-omero-web/pull/18
