### ISSUE TITLE
Add omero_web_python_addons to preinstall additional pip packages

### ISSUE THREAD

**Issue by manics** [ome/ansible-role-omero-web#20]
https://github.com/ome/ansible-role-omero-server/pull/36 includes the parameter `omero_server_python_addons` to install pip packages when the venv is created. An analogous parameter could be added to this role to simplify installation of web apps.
- See https://github.com/ome/prod-playbooks/pull/182

You'll need to duplicate the task https://github.com/ome/ansible-role-omero-web/blob/2.0.2/tasks/web-install.yml#L119 since omero.web includes a requirements file (unless you want to decouple omero.web so it's pip installable 😀)

**Comment by joshmoore** [comment]
> unless you want to decouple omero.web so it's pip installable

I would think that will be achieved by the end of the year.
