### ISSUE TITLE
Update Role to work with Ubuntu 22.04 Rocky Linux 9

### ISSUE THREAD

**Issue by JulianHn** [ome/ansible-role-omero-web#46]
Just to avoid multiple people taking the same role to update (cf. https://github.com/ome/omero-server-docker/issues/79 / https://github.com/ome/omero-web-docker/issues/74) I am opening an issue here, so people can claim that specific role to work on.

@glyg It seems like you already started work on this?

**Comment by glyg** [comment]
Yes I started looking into it yesterday, but have not advanced much, I was not sure how to manage role dependencies. I plan to work on that today and tomorrow

**Comment by pwalczysko** [comment]
As indicated on other issues (sorry for the multiple pings, just do not want you @glyg to miss it to prevent double efforts), please see https://github.com/ome/ansible-role-omero-web/pull/48

**Comment by glyg** [comment]
THanks @pwalczysko and @sbesson Does this means I shall close #47 ? Sorry I could not get to it sooner

**Comment by pwalczysko** [comment]
> THanks @pwalczysko and @sbesson Does this means I shall close #47 ? Sorry I could not get to it sooner

No need to apologize. We just needed to cater for our own needs and went ahead with the work you so nicely started. I think yes, you can close #47 if you wish. 
Thank you again. Note that we are not fully satisfied with the failing test on Ubuntu22.04 on #48, but we will keep you informed on further course of action on that one.
